const app = document.querySelector('#app');
const moods = [
  ['calm','Calm','A little room to breathe.','landscape'],['dreamlike','Dreamlike','Somewhere beyond the everyday.','moon'],
  ['intense','Intense','Something that stays with you.','storm'],['warm','Warm','Light, colour, a familiar feeling.','flowers'],
  ['melancholic','Melancholic','Beauty with a quieter edge.','winter'],['curious','Curious','An unexpected way of seeing.','animals'],
];
const state = { feeling:null, answers:[], filters:{}, excluded:[], anchor:'', results:[],total:0,view:'gallery',done:false,offset:0 };
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const imageUrl = value => /^https:\/\/api\.nga\.gov\//.test(value || '') ? value : '';
let request, selected, detailRequest;
const startSubjects = {
  calm:[['water','By the water'],['garden','In a garden'],['portrait','With a person'],['landscape','Out in nature']],
  dreamlike:[['moon','Under the moon'],['night','After dark'],['dream','Inside a dream'],['mythology','Myths & stories']],
  intense:[['storm','Forces of nature'],['battle','Human conflict'],['fire','Light & fire'],['portrait','An arresting face']],
  warm:[['flowers','Flowers & growth'],['summer','Summer days'],['family','Family & belonging'],['sun','Sunlight']],
  melancholic:[['winter','Winter landscapes'],['ruins','Traces of time'],['portrait','A human presence'],['night','A quiet night']],
  curious:[['animals','The animal world'],['architecture','Built spaces'],['study','Studies & details'],['mythology','Stories & symbols']],
};
function nextQuestion() {
  if(state.done || state.answers.length>=3) return null;
  const answered = new Set(state.answers.map(a=>a.kind));
  if(!answered.has('subject')) return {kind:'subject',title:'Where does this<br>feeling take you?',desc:'Choose a subject to follow, or leave the possibilities open.',options:startSubjects[state.feeling]};
  if(!answered.has('medium')) return {kind:'medium',title:'What kind of mark<br>draws you in?',desc:'A painted surface, a drawn line, or a moment captured.',options:[['Painting','Painted colour'],['Drawing','Lines & gestures'],['Print','Print & impression'],['Photograph','A photographic eye']]};
  return {kind:'period',title:'A time you want<br>to wander through?',desc:'Keep exploring freely, or choose a chapter in the collection.',options:[['early','Before 1800'],['nineteenth','The 19th century'],['modern','1900 onwards']]};
}
function landing() {
  app.innerHTML=`<section class="landing"><div class="intro"><h1>You don’t need the words.<br>Start with <i>a feeling.</i></h1><p>Let a feeling lead you to art.<br>Follow what catches your eye.<br>Go deeper when you’re ready.</p></div><div class="feeling-grid">${moods.map(([id,name,desc])=>`<button class="feeling" data-feeling="${id}"><div class="feeling-art" id="cover-${id}" aria-hidden="true"></div><span class="feeling-name">${name}<b>↗</b></span><small>${desc}</small></button>`).join('')}</div><div class="landing-bottom"><form class="free-search" id="free-search"><input aria-label="Search an idea or subject" name="q" placeholder="Or follow your own idea…" required><button aria-label="Explore your idea">↗</button></form><p>Real artworks from the National Gallery of Art.<br>No art-history knowledge needed. Just curiosity.</p></div></section>`;
  moods.forEach(async([id,,,q])=>{try{const res=await fetch('/api/discovery?'+new URLSearchParams({feeling:id,q,medium:'Painting'}));const data=await res.json();const node=document.querySelector('#cover-'+id);if(node&&data.results?.length){const row=data.results[Math.min(1,data.results.length-1)];node.innerHTML=`<img src="${esc(imageUrl(row.thumbnailUrl))}" alt="" title="${esc(row.title)}">`;}}catch{const node=document.querySelector('#cover-'+id);if(node)node.textContent='Explore the collection';}});
}
function tokens(){
  const items=[{label:moods.find(m=>m[0]===state.feeling)?.[1],key:'feeling'}];
  state.answers.filter(a=>a.value).forEach(a=>items.push({label:a.label,key:a.kind}));
  Object.entries(state.filters).filter(([,v])=>v).forEach(([k,v])=>items.push({label:k==='from'?`After ${v}`:k==='to'?`Before ${v}`:v,key:'filter:'+k}));
  if(state.anchor!=='')items.push({label:'Visual anchor',key:'anchor'});
  if(state.excluded.length)items.push({label:`${state.excluded.length} hidden`,key:'excluded'});
  return items.map(t=>`<button class="token" data-remove="${esc(t.key)}" aria-label="Remove ${esc(t.label)}">${esc(t.label)} <span>×</span></button>`).join('');
}
function shell(){const q=nextQuestion();app.innerHTML=`<div class="explore-shell"><aside class="journey"><button class="back" data-home>← Start again</button><div class="trail-title">YOUR EXPLORATION</div><div class="trail">${tokens()}</div><div class="progress"><span style="width:${Math.min(100,(state.answers.length+1)*25)}%"></span></div>${q?`<div class="question-count">A LITTLE DIRECTION · ${state.answers.length+1} OF 3</div><h2>${q.title}</h2><p>${q.desc}</p><div class="answers">${q.options.map(([value,label])=>`<button class="answer" data-answer="${esc(value)}" data-label="${esc(label)}" data-kind="${q.kind}">${label}<span>↗</span></button>`).join('')}</div><button class="quiet skip" data-skip="${q.kind}">Keep it open — skip this question</button>`:`<h2>See what<br><i>stays with you.</i></h2><p>Your trail is a starting point. Open a work, compare its details, or remove a choice to explore further.</p><button class="quiet skip" data-restart>Revisit the questions</button>`}<div class="research-entry"><p>Have something more<br>specific in mind?</p><button class="primary" data-research>Research filters <span>↗</span></button></div><p class="subtle-note">Feelings open suggested catalogue themes. They don’t assign an emotion to a work.</p></aside><section class="results" aria-label="Artwork results"><div class="result-heading"><h2>A feeling, <i>taking shape.</i></h2><div class="view-switch" aria-label="Result view"><button data-view="gallery" class="${state.view==='gallery'?'active':''}" aria-pressed="${state.view==='gallery'}">Gallery</button><button data-view="list" class="${state.view==='list'?'active':''}" aria-pressed="${state.view==='list'}">List</button></div></div><div class="result-meta"><span id="result-count" aria-live="polite">Finding your way through the collection…</span><button class="quiet" data-about>Why these works?</button></div><div id="artworks" class="loading">Gathering artworks…</div><div id="load-more"></div></section></div>`;}
function params(){const p={feeling:state.feeling,...state.filters,offset:state.offset,exclude:state.excluded.join(',')};for(const a of state.answers){if(!a.value)continue;if(a.kind==='subject'&&!p.q)p.subject=a.value;if(a.kind==='medium'&&!p.medium)p.medium=a.value;if(a.kind==='period'&&!p.from&&!p.to){if(a.value==='early')p.to=1799;if(a.value==='nineteenth'){p.from=1800;p.to=1899;}if(a.value==='modern')p.from=1900;}}if(state.anchor!=='')p.anchor=state.anchor;return new URLSearchParams(p);}
async function load(append=false){request?.abort();request=new AbortController();document.querySelector('.results')?.setAttribute('aria-busy','true');try{const res=await fetch('/api/discovery?'+params(),{signal:request.signal});const data=await res.json();if(!res.ok)throw Error(data.error||'The collection is unavailable.');state.results=append?[...state.results,...data.results]:data.results;state.total=data.total;paintResults();}catch(err){if(err.name==='AbortError')return;document.querySelector('#artworks').className='empty';document.querySelector('#artworks').innerHTML=`<h3>A pause in the exploration.</h3><p>${esc(err.message)}</p><button class="quiet" data-retry>Try again</button>`;document.querySelector('#result-count').textContent='Could not load artworks';}finally{document.querySelector('.results')?.setAttribute('aria-busy','false');}}
function paintResults(){const container=document.querySelector('#artworks');if(!container)return;document.querySelector('#result-count').textContent=`${state.total.toLocaleString()} works on this trail · ${state.results.length} shown`;container.className=state.results.length?(state.view==='list'?'art-list':'art-grid'):'empty';container.innerHTML=state.results.length?state.results.map((row,i)=>`<button class="art-card" data-art="${row.id}"><div class="art-image"><img src="${esc(imageUrl(row.thumbnailUrl))}" alt="${esc(row.title)}" loading="lazy"></div><div class="art-caption"><span class="index">${String(i+1).padStart(2,'0')} / ${esc(row.classification)}</span><h3>${esc(row.title)}</h3><p>${esc(row.artist?.replace(/^[;\s]+$/,'')||'Artist not listed')}<br>${esc(row.date||'Date not listed')}</p>${state.view==='list'?`<p>${esc(row.medium)}</p><div class="reason">${row.reasons.map(esc).join('<br>')}</div>`:''}</div></button>`).join(''):`<h3>A little too specific?</h3><p>No works match this combination.<br>Remove a choice from your trail or open the research filters.</p><button class="quiet" data-research>Adjust filters</button>`;document.querySelector('#load-more').innerHTML=state.results.length<state.total?'<button class="more" data-more>Explore more works ↓</button>':'';}
function refresh(){state.offset=0;shell();load();}
function start(feeling,q=''){state.feeling=feeling;state.answers=[];state.filters=q?{q}:{};state.excluded=[];state.anchor='';state.done=false;state.results=[];refresh();window.scrollTo(0,0);}
function openResearch(){const form=document.querySelector('#research-form');form.reset();const effective=Object.fromEntries(params());effective.q=effective.q||effective.subject||'';for(const [key,value] of Object.entries(effective))if(form.elements[key])form.elements[key].value=value;document.querySelector('#filter-error').textContent='';document.querySelector('#research').showModal();}
async function openArt(id){const row=state.results.find(a=>a.id===id);if(!row)return;selected=row;detailRequest?.abort();detailRequest=new AbortController();const dialog=document.querySelector('#detail');dialog.innerHTML=`<div class="detail-layout"><div class="detail-visual"><img src="${esc(imageUrl(row.thumbnailUrl))}" alt="${esc(row.title)}"></div><div class="detail-copy"><div class="dialog-top"><span>LOOKING CLOSER</span><button class="close" data-close="detail" aria-label="Close artwork">×</button></div><h2>${esc(row.title)}</h2><p>${esc(row.artist?.replace(/^[;\s]+$/,'')||'Artist not listed')}</p><div class="metadata">${esc(row.date)}<br>${esc(row.medium)}</div><h3>ON YOUR TRAIL</h3><p>${row.reasons.map(esc).join('<br>')}</p><div class="detail-actions"><button data-anchor ${row.hasVector?'':'disabled'}>More like this ↗</button><button data-less>Hide this work</button></div>${!row.hasVector?'<p class="micro">Visual comparison is not indexed for this work yet.</p>':''}<h3>CATALOGUE THEMES</h3><div class="detail-tags">${esc(row.terms||'No subject terms listed.')}</div><div id="dna-reading"></div><a class="source-link" href="${esc(/^https:\/\/www\.nga\.gov\//.test(row.objectUrl)?row.objectUrl:'https://www.nga.gov/') }" target="_blank" rel="noopener">View the NGA catalogue record ↗</a></div></div>`;dialog.showModal();try{const res=await fetch('/api/artwork-dna/'+id,{signal:detailRequest.signal});if(!res.ok)return;const data=await res.json();if(selected?.id!==id)return;document.querySelector('#dna-reading').innerHTML=`<details><summary style="margin-top:24px;cursor:pointer">Artwork DNA · supporting reading</summary><p class="micro">Relative model matches, not emotional certainty.</p><p>${data.modelReading.scores.slice(0,3).map(s=>esc(s.label)+' · '+s.score.toFixed(3)).join('<br>')}</p><h3>COLOURS FROM THE IMAGE</h3><div class="palette">${data.visual.palette.map(s=>`<span style="background:${/^#[0-9A-F]{6}$/i.test(s.hex)?s.hex:'#ccc'}" title="${esc(s.hex)}" aria-label="${esc(s.hex)}"></span>`).join('')}</div></details>`;}catch{}}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.close){document.querySelector('#'+b.dataset.close).close();return;}if(b.id==='about-open'||b.hasAttribute('data-about')){document.querySelector('#about').showModal();return;}if(b.dataset.feeling){start(b.dataset.feeling);return;}if(b.hasAttribute('data-home')){request?.abort();state.feeling=null;landing();return;}if(b.dataset.answer){state.answers.push({kind:b.dataset.kind,value:b.dataset.answer,label:b.dataset.label});refresh();return;}if(b.dataset.skip){state.answers.push({kind:b.dataset.skip,value:'',label:''});refresh();return;}if(b.dataset.remove){const key=b.dataset.remove;if(key==='feeling'){state.feeling=null;request?.abort();landing();return;}if(key==='anchor')state.anchor='';else if(key==='excluded')state.excluded=[];else if(key.startsWith('filter:'))delete state.filters[key.slice(7)];else {state.answers=state.answers.filter(a=>a.kind!==key);state.done=false;}refresh();return;}if(b.hasAttribute('data-research')){openResearch();return;}if(b.hasAttribute('data-restart')){state.answers=[];state.done=false;refresh();return;}if(b.dataset.view){state.view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});paintResults();return;}if(b.hasAttribute('data-more')){state.offset=state.results.length;load(true);return;}if(b.hasAttribute('data-retry')){load();return;}if(b.dataset.art){openArt(Number(b.dataset.art));return;}if(b.hasAttribute('data-anchor')){state.anchor=selected.id;document.querySelector('#detail').close();refresh();return;}if(b.hasAttribute('data-less')){state.excluded.push(selected.id);document.querySelector('#detail').close();refresh();return;}if(b.id==='reset-filters'){state.filters={};document.querySelector('#research').close();refresh();}});
document.addEventListener('submit',event=>{if(event.target.id==='free-search'){event.preventDefault();start('curious',new FormData(event.target).get('q').trim());}if(event.target.id==='research-form'){event.preventDefault();const values=Object.fromEntries(new FormData(event.target));if(values.from&&values.to&&Number(values.from)>Number(values.to)){document.querySelector('#filter-error').textContent='The start year must be before the end year.';return;}state.filters=values;state.answers=[];state.done=true;document.querySelector('#research').close();refresh();}});
document.addEventListener('error',event=>{if(event.target.tagName==='IMG'){event.target.style.display='none';const p=event.target.parentElement;p.setAttribute('aria-label','Artwork image unavailable');p.insertAdjacentHTML('beforeend','<span class="micro">Image unavailable</span>');}},true);
for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
if(location.protocol==='file:')app.innerHTML='<section class="landing"><h1>Open the live exploration.</h1><p>Search needs the local collection server.</p><a href="http://localhost:4173/">Open localhost:4173 ↗</a></section>';else landing();
